[package]
name = "seven_zipper"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.29.1"
eframe = "0.29.1"
zip = "2.2.1"
rfd = "0.15.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
rayon = "1.10.0"
crossbeam-channel = "0.5.13"